#cd C:\Users\Hasan\Desktop\payment-tracking
#docker-compose -f docker-compose.yml up

version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER : htnc
      POSTGRES_PASSWORD: 123

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: htnc
      MONGO_INITDB_ROOT_PASSWORD: 123